[programs.localnet]
solana_twitter = "E3fVW6wcX5y3SMzb12NefNtvUjUWDxjLKuPRY6THFmVY"

[programs.devnet]
solana_twitter = "E3fVW6wcX5y3SMzb12NefNtvUjUWDxjLKuPRY6THFmVY"

[programs.mainnet]
solana_twitter = "E3fVW6wcX5y3SMzb12NefNtvUjUWDxjLKuPRY6THFmVY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/hevarabrihem/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
